legacy_layout=false
horizontal
fps
fps_metrics=0.01
frametime=0
frame_timing=0
background_alpha=0.0
alpha=0.4
position=bottom-left
font_size=18
fps_limit_method=late
fps_limit=162
toggle_fps_limit=Shift_L+F1
toggle_hud=Shift_R+F12
